---

nginx_server_name: "{{ hostname }}"

nginx_config_http_template_enable: true
nginx_config_http_template:
  app.nicko.cc:
    servers:
      http:
        listen:
          listen_localhost:
            port: 80

        server_name: "{{ nginx_server_name }}"
        https_redirect: "{{ nginx_server_name }}"

      https:
        listen:
          listen_localhost:
            port: 443
            ssl: true

        server_name: "{{ nginx_server_name }}"

        ssl:
          cert: "/etc/letsencrypt/live/{{ nginx_server_name }}/fullchain.pem"
          key: "/etc/letsencrypt/live/{{ nginx_server_name }}/privkey.pem"

        web_server:
          locations:
            root:
              location: /
              html_file_location: /usr/share/nginx/html
              html_file_name: index.html
