---

nginx_worker_processes: auto
nginx_http_params:
  - server_tokens off
  - log_format  kv  '$time_iso8601 '
                    '$msec '
                    'host'            '=$host '
                    'server'          '=$server_name '
                    'request'         '="$request" '
                    'status'          '=$status '
                    'cache'           '=$upstream_cache_status '
                    'upstream_status' '=$upstream_status '
                    'upstream_addr'   '=$upstream_addr '
                    'time'            '=${request_time}s '
                    'upstream_time'   '=${upstream_response_time}s '
                    'in'              '=${request_length}B '
                    'out'             '=${bytes_sent}B '
                    'body'            '=${body_bytes_sent}B '
                    'referer'         '="$http_referer" '
                    'remote'          '=$remote_addr '
                    'user'            '=$remote_user '
                    'ua'              '="$http_user_agent"'
  - access_log /var/log/nginx/access.log kv buffer=64k flush=10s
  - error_log /var/log/nginx/error.log warn
  - proxy_cache_path /tmp/nginx-cache levels=1 keys_zone=ASSET_CACHE:10m max_size=1000m inactive=600m
  - proxy_temp_path /tmp/nginx-tmp
